name: TishApp
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider:
  localstorage:
  # flutter_facebook_auth: ^3.5.0
  universal_platform: ^1.0.0+1
  oauth2: ^2.0.0
  shared_preferences:
  http_interceptor: ^1.0.1
  jwt_decode: ^0.3.1
  dio: ^4.0.0-prev2

  # connectivity: ^3.0.6

  # Base
  cupertino_icons: ^1.0.3
  nb_utils: ^4.2.11
  intl: ^0.17.0
  flutter_vector_icons: ^1.0.0
  google_fonts: ^2.1.0

  # Common
  share: ^2.0.4
  url_launcher: ^6.0.3
  http: ^0.13.3
  html: ^0.15.0
  package_info: ^2.0.2

  # IMAGES
  cached_network_image: ^3.0.0
  image_picker: ^0.8.2
  file_picker: ^3.0.1

  # AUTHENTICATION
  local_auth: ^1.1.6

  # STATE MANAGEMENT
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0

  # MAP
  location: ^4.2.0
  google_maps_flutter: ^2.0.6

  # WEB TOOLS
  webview_flutter: ^2.0.8

  # UI
  simple_animations: ^3.1.1
  flutter_svg: ^0.22.0
  flutter_slidable: ^0.6.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_staggered_animations: ^1.0.0
  flutter_colorpicker: ^0.4.0
  signature: ^4.1.1
  dots_indicator: ^2.0.0
  percent_indicator: ^3.0.1
  flutter_rating_bar: ^4.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  animations: ^2.0.0
  lottie: ^1.0.1
  liquid_swipe: ^2.1.0
  flutter_reaction_button: ^1.0.8

  flutter_localizations:
    sdk: flutter

  #Temporary  disable duo to late of null safety

  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.4
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true

  assets:
    - images/imageTest.jpeg
    - assets/
    - assets/integrations/lang/
    - assets/shophop_data/
    - images/app/icons/
    - images/app/
    - images/app/ic_rate_app.png
    - images/TishApp/
    - assets/medium/mediumhtmlpage.html
    - images/grey.jpg

    - assets/integrations/map_point.json
    - assets/defaultTheme/
    - assets/cricket_data/
    - lang/en.json
    - lang/hi.json

  fonts:
    - family: Andina
      fonts:
        - asset: fonts/andina.ttf

    - family: Regular
      fonts:
        - asset: fonts/googlesansregular.ttf

    - family: Medium
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Semibold
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Bold
      fonts:
        - asset: fonts/googlesansebold.ttf
